services:
  backend:
    build: ./backend
    container_name: leancon-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/ifc:/app/ifc
    environment:
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: leancon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: leancon-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
